apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstspringboot
spec:
  selector:
    matchLabels:
      app: springbootapp
  replicas: 1
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
      - name: firstspringbootpod
        image: ${REPOSITORY_TAG}
        imagePullPolicy: Never
